-include make-do.mk

halp:
	@ echo use the source, Luke

include $(MAKE_DO_INSTALL)/mdo-util/module-init.mk
include $(MAKE_DO_INSTALL)/mdo-util/macro.mk
include $(MAKE_DO_INSTALL)/mdo-util/generate-cmd.mk
include $(MAKE_DO_INSTALL)/mdo-util/install-cmd.mk
