#!/bin/bash

if [ ! -f Makefile ] && [ ! -f makefile ]; then
  echo "include make-do.mk" | make -I /usr/local/include/make-do/util -f - "$@" 2>/dev/null
else
  make -I /usr/local/include/make-do/util "$@"
fi
