#!/bin/bash

# invoke make with the make-do library on the include path
# no-built-in : skip all that archaic compiler stuff:
# quiet: shush. Use --trace to override.
MAKE_CMD='make -I /usr/local/include/make-do/includes --no-builtin-rules --no-builtin-variables --quiet'

if [ ! -f Makefile ] && [ ! -f makefile ]; then
  # we must not be in a make-do-module, so we must include the lib
  echo "include make-do.mk" | ${MAKE_CMD} -f - "$@" 2>/dev/null
else
  ${MAKE_CMD} "$@"
fi
